### ISSUE TITLE
Double emotes for held micros

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#133]
Micros being held get double emotes. Everyone's, and their own, are printed twice in the chat window.

**Comment by Leshana** [comment]
Additional information: This actually also happens for people eaten by the predator IF the predator happens to be holding a micro!
Analysis: This happens only when the pred has the PASSEMOTES status flag set.  That status flag causes the pred to pass emotes on to holders inside them.   However, due to new enhanced emote code, this is actually no longer necessary.

**Comment by OrbisAnima** [comment]
Doesn't this also happens when inside the cockpit of mechs? I will investigate it in a bit if it wasn't a weird instance, but I am almost sure it happened with pods and ripleys

**Comment by nightwingthedragon** [comment]
Odd, I'd have thought this was caused by adding the PASS_EMOTES flag in the "holder" class? Ah well.

**Comment by Arokha** [comment]
This was fixed.
