### ISSUE TITLE
Sergals and Akula lack primitive species.

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#216]
Akula need to be shark pups.

http://i46.tinypic.com/4k9rsx.png

And Sergals... I.. honestly have no idea. Just smaller sergals. Baby sergals. >.> Sergal pups.

These were supposed to get added and never did.

**Comment by Screemonster** [comment]
https://www.dropbox.com/s/ygmikd1czg225ai/sharkpup.dmi?dl=0

I'll do sergals in a bit, but there's a sharkpuppy.

**Comment by SpadesNeil** [comment]
As for sergals?

**Comment by Screemonster** [comment]
Well. Did some googlin'.
http://goldring.wikia.com/wiki/Sergals#Trivia
This was what the early pictures of sergals started like before the artist properly developed them, so I'mma make the unevolved versions look like that as a lil' nod to that.

**Comment by Screemonster** [comment]
https://www.dropbox.com/s/21ref9v0igak1p4/sergal.dmi?dl=0 Done.

**Comment by SpadesNeil** [comment]
uni_append = list(0x0A0,0xE00,0x00,0x00,0x00,0x999) // 0A0E00

So now I have to figure out what the hell this is.
@ShadowLarkens halp

**Comment by ShadowLarkens** [comment]
@SpadesNeil An absolutely mental way to write bitflags, not sure how it works exactly.

**Comment by SpadesNeil** [comment]
I found it under the monkey mobs.

**Comment by SpadesNeil** [comment]
So what do I need to do to make my own version for new species, @ShadowLarkens ?

**Comment by nightwingthedragon** [comment]
Okay so I have no knowledge of bitflags or anything of the sort, but I can slightly interpret that.

uni_append - figure out what exactly this variable does, go hunting for it. I'm guessing it might have something to do with genetics code.

list - also obvious. The list is thus printed:

-0x0A0
-0xE00
-0x00
-0x00
-0x999

Looking at the comment next to it, it seems the first two entries are important? 0A0 E00
That looks like hexadecimal to me, but I could of course be wrong. Since I don't know anything about bit fields, this is as far as I can get. Just figure out what uni_append is for and how 0A0E00 is relevant to that.

**Comment by SpadesNeil** [comment]
But what does the hexidecimal correspond to? Color? Something else? Looks like color to me.

**Comment by SpadesNeil** [comment]
Fixed in current version.
