### ISSUE TITLE
Pill bottles

### ISSUE THREAD

**Issue by Treasa729** [SpadesNeil/VOREstation#258]
While science used to have pill bottles at their chemistry station on the outpost, they got removed and there is no way to actually get any. Medical has a very limited stock of 2 boxes of pill bottles which they will almost never give out, and there is no way to order them from cargo. Would it be possible to add a crate for pill bottles which could be ordered from cargo, or just stock medical and/or science with more?

**Comment by Arokha** [comment]
What do you need pill bottles for?

**Comment by Treasa729** [comment]
Generally, stuff like away missions, Many times the RD, or scientists end up acting like medical staff if there aren't a whole lot around at the time, and as such, it'd be good to have the bottles there as an option since most of the time medical isn't willing to give their limited stock up and such. It wouldn't be needed all the time, so I think it would be helpful to have that as an option, (and as such, cargo crates so that they can be ordered if they're needed) since right now neither medical nor science can actually get their hands on any more pill bottles, and I've talked to a few people in medical as well who wish that there were more pill bottles around, or a way to get more.

**Comment by Arokha** [comment]
That's not a reason to make science able to do medical's job, that's a reason to make medical do their job better. Also 14 pill bottles hold 14 pills each with 60u of drugs in each for 11,760u of drugs in pill bottles without ordering anything from cargo. That seems pretty decent to me. XD

Maybe medical can have another box, but even on old code they only had 2 boxes of pill bottles so this isn't something that changed. I'm opposed to giving science pill bottles, however, since that's making one department start to encroach onto others.

**Comment by SpadesNeil** [comment]
No pill bottles for science. Your chemistry lab isn't meant for that.
