### ISSUE TITLE
Purchasable Pets

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#270]
Pet vendor (AniVend?) that vends cybernetic pets. I can code this. This is here for comments, not seeking a coder. This is sorta a long-term-ish project.

My thoughts are these:

-Take pinpointer sprite, modify it and attach a 'capsule' to the side that you can remove.
-Throwing capsules deploys pets, and makes pinpointer show you where they are.
-They are cybernetic so eating them doesn't do anything unless you enable their digestability using your pad thing. They are, however, prohibitively expensive to keep them from being a common food source.

**Comment by Treasa729** [comment]
I think it could be interesting, especially if it would be possible to have them as something you can get in character creation as well so they're more like pets and you wouldn't have to worry about the game starting you with almost no cash in your account and being unable to buy your favourite pet! D: (Already a bit of an issue with laptops, it would probably be good to make the heads start out with more cash in their accounts so that they can buy stuff like fully built laptops or whatever else)
