### ISSUE TITLE
'Draining' digestion mode

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#273]
As suggested by a player:

A digestion mode that drains nutriment from people in nonfatal ways, then knocks the prey out when they run out of nutriment.

**Comment by Treasa729** [comment]
I think this would definitely be interesting, that, and possibly some other nonfatal digestion options, like mechanics for nonlethal absorption and stuff too! :D

**Comment by SpadesNeil** [comment]
I'd be okay with this.

**Comment by Screemonster** [comment]
I'm okay with this. I've RP'd out that sorta thing, and endo where the pred still gets something out of it (and therefore a reason to hunt and be predatory) is neat.
Would ALSO add a means for nonlethal predators to actually incapacitate endo prey (and effectively remove them from play) rather than just relying on the honour system for them to not inflict unavoidable internal beatings. 

Absorption is something I think nightwing is working on with the custom internal spaces and the ability to move prey around - just make a belly area for your pudge, move the prey into it, then drain them until they're KO'd.

So, yes. Between those two, either alone or in combination, that's a great big widening of the options for folks that like endo that goes a little further than just holding.

**Comment by Arbon777** [comment]
Seeing as if one is mechanically unconscious (likewise when mechanically blind) they are basically trapped in the no-fun corner incapable of even observing the game and chatting around the way you can when actually killed, I would steer far, far away from anything that keeps people unconscious for an extended period of time. Go with paralytics instead, and some muffling option the predator can have that locks the prey into only using that new "Subtle" message. Still able to hear, still able to see, still IN THE GAME and not just looking at a blank screen with "You almost heard something" messages spamming.

**Comment by Screemonster** [comment]
I'd agree with that, locking people out by making them actually unconscious is bad for RP. Add a "drained" flag or something to people that locks them in the resting state until shaken awake or something.
