### ISSUE TITLE
Perscription glasses should be usable on HUD and Mesons and other eyewear to upgrade it

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#306]
To fix the problem of there being no prescription variants of eyewear vital to gameplay in many cases, I propose we edit the prescription glasses in our code. If you click on another bit of utility eyewear like mesons, thermals, or HUDs, it should delete the prescription glasses and set the target glasses to prescription = 1, using very similar code to PDA conversion kits.

It'd be an easy few lines of code. I'll do it myself if no one else does. I'm just busy elsewhere right now.

**Comment by Treasa729** [comment]
I think it'd be better if possible to have the eyewear used on the glasses and have them 'scan' the prescription of the glasses or something like that so that you'd be able to get perscription thermals, mesons, or whatever and not be forced to wear them all the time like you would have to if it used up the glasses. It would also make more sense ICly, than treating it like a conversion kit since a lot of things like the medical huds don't actually have lenses you could switch out and so you couldn't say hat you were replacing the lenses. This is definitely a big thing though, mechanically, I stopped having my character wear glasses because it was too much of a pain to not be able to use any of the huds at all. Another option would be to add the ability to 'attach' mesons, sechud, whatever to the prescription glasses like you can medals and such or vise versa to wear them over eachother. Either of these would probably work out much better in terms of making sense than simply having the glasses work like kits. Either way though, regardless of how this is handled, I think that it'd be awesome to actually have a way to get prescription huds.

**Comment by SpadesNeil** [comment]
That doesn't really make a ton of sense actually. I'm doing it my way.
