### ISSUE TITLE
Naga tail + bat wings incompatibility

### ISSUE THREAD

**Issue by ZodiacShadow** [SpadesNeil/VOREstation#313]
I haven't tried out other taur-body/demi-parts-combos, but setting taur body to Naga and the custom "tail" to "Red bat wings", means that the bat wings do not show.
I could've sworn this has worked before, but then again, I haven't used the character in question much since the implementation of accesory-less demi parts.
I can use the naga tail with the wing accessory just fine, but then I'm back to being unable to wear headwear.

**Comment by OrbisAnima** [comment]
A proposed solution would be to implement the wings slot, but it would require reformating of quite a bit of rework thanks to how layers work in the code, the other alternative is to have naga tails and taurs bodies be on a lower layer, but I don't know how that would impact on many other characters, thus, I would suggest you summon the @nightwingthedragon

**Comment by Arokha** [comment]
This will never look right, unfortunately. Any two things which, from some angles should be above and some angles should be below, and where one of the things may or may not exist, will be difficult/impossible to implement. The game has very few things which 'occlude' other things, really. Most of the time it is just that the sprite isn't drawn for the wings in the 'facing south' sprite except for the edges. Stuff like that isn't even a layering thing, because the wings ARE on a higher layer than the body.

But for stuff like wings, when you're facing west, have a naga tail, it should occlude the far wing and not the near one, like stuff like that isn't really do-able without reworking how update_icons works entirely, and then dividing all the sprites into like... 'close side of tail' and 'far side of tail' sprites and it's just kinda messy.
