### ISSUE TITLE
Add feature to select character weight and metabolism in character menu.

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#358]
Issue relies on #357 being completed.

- Allow players to set a body weight in their character menu. Options should exist for both pounds and kilograms, but convert to pounds in the code.
- Allow players to set their weight_gain rate between 0% and 100% (100% by default)
- Allow players to set their weight_loss rate between 0% and 100% (50% by default)
- Convert weight_gain and weight_loss to a decimal by multiplying input value by 0.01 before it reaches the weight_gain and weight_loss variables in life.dm

**Comment by SilverTalismen** [comment]
I think the weight should be set abit higher or rely on character size and stuff

**Comment by SpadesNeil** [comment]
@Cameron653 @nightwingthedragon I don't know how character setup works halp.

**Comment by Arokha** [comment]
You didn't @ me but I'm here anyway because WHATEVER GOSH HECKIE.

You need to change character setup but you also need to make a place in the save files that it can save this setting to when they click save.

The former is in preferences.dm and is somewhat annoying. There are 3 general sections to the file. The top that actually sets up vars but these are just temporary, not actual vars on the character. These vars get put into the save file, or put into actual mob vars later. The middle, which defines all the properties on the character setup screen, and the end which is a function that dumps all the vars into a character when they spawn.

With tail_style as an example... at the top there's:

`var/tail_style = null				//Tail style`
Just making the blank var to be filled in later from loading or from user choice.

`dat += "Tail Style: <a href='byond://?src=\ref[user];preference=tail_style;task=input'>[tail_style ? "Custom" : "Normal"]</a><br>"`
This is the actual HTML on the character setup page for picking it. It has some logic in it for tail_style (ternary operator "if tail_style is defined then "Custom" else "Normal""). The magic here is the stupid preferece=tail_style part, which refers to...

`				if("tail_style")
					var/list/pretty_tail_styles = list("Normal")
					for(var/path in tail_styles_list)
						var/datum/sprite_accessory/tail/instance = tail_styles_list[path]
						if((!instance.ckeys_allowed) || (usr.ckey in instance.ckeys_allowed))
							pretty_tail_styles[instance.name] = path
					var/selection = input(user, "Pick tail (doesn't update preview)", "Character Preference") as null|anything in pretty_tail_styles
					if(selection && selection != "Normal")
						tail_style = pretty_tail_styles[selection]
					else
						tail_style = null`
This section. Which actually generates the little dialog box (the input function) and takes the input and saves it as the var. There's some magic for tail_style. You can steal age or something if you want numerics, or make a list of choices like tail_style has (defined in global lists). Way later...

`character.tail_style = tail_styles_list[tail_style]`
in the copy_to function. The copy_to function actually does the copying to the mob when they spawn, so you set character.whatever the var on the mob is equal to whatever your temp var you defined earlier was. Make them the same name if you want to live.

The latter is in preferences_savefile.dm and if you look at it, just... copy whatever the other vars have. It's fairly self-explanatory. Need to modify both the save and load sections. Just copy what the other vars do and use your own var names.

**Comment by Arokha** [comment]
In retrospect I could have used scale as an example but I was COMMITTED to my example once I started. Maybe look at scale, but the above should explain how the file works and what to change, anyway.

**Comment by SpadesNeil** [comment]
So I have some code to look at and test.

**Comment by SpadesNeil** [comment]
https://github.com/SpadesNeil/VOREstation/commit/507691666fdf5a799bfbcfa20fcb8779a9648fd7

I think I'm done here.

**Comment by Cameron653** [comment]
Going to compile and give it a test.

**Comment by SpadesNeil** [comment]
We're hitting a roadblock where tie variables are not changing in-game when the character profile is edited.

**Comment by Cameron653** [comment]
Tested and everything appears to be working. High nutrition gives weight, no nutrition makes you lose weight. Variables appear to save.
