### ISSUE TITLE
Holodeck controls are accessible from outside the locked holodeck.

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#402]
Am starting to get tired of people messing with the holodeck program despite the windows being blacked out and the door bolt lights being lit up in an obvious clue to anyone with a functioning brain that people are in there trying to have a scene.

Propose having the door bolt controls lock the yellow-striped door and only allow access to the controls from the holodeck itself via the other door. Maybe put a HoS-access button outside to allow them to gain entry (as per locked dorms)

**Comment by Screemonster** [comment]
Okay, looking at it, the yellow door is maintenance access which is a start, but maybe that's not enough of a deterrent to people messing with it since quite a lot of jobs have maint access.

**Comment by SpadesNeil** [comment]
If people waltz in at this point and screw with it I'm pretty sure they're just dense idiots. I do not know how to make this any better at this point and I do not want to move the controls to the opposite side of the room, because unlike dorms, if you have to break into the Holodeck to fix something or save someone, it's either unbolt the door or shatter irreparable windows.

**Comment by SpadesNeil** [comment]
If anyone messes with the map though it'll be me.

**Comment by SilverTalismen** [comment]
Couldn't you have it so it bolts the maitenence door, but add a emergency unlock button that a Head of Staff can swipe their card through to unbolt the doors so they can get in?

**Comment by SpadesNeil** [comment]
Is this still a problem?
