### ISSUE TITLE
Hostile vore mob framework

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#486]
Nightwing! I just realized there wasn't a Github issue for this which is probably why it hasn't gotten done yet.

So it's here now!

Vore mobs should have the following features:

- <s>Vore mobs should have basic code framework under /mob/living/simple_animal/hostile/vore and I'll worry about adding additional mobs.</s>
- <s>Vore mobs should only engage targets who are not in the same faction as they are. If the vore code is injected into the attack proc, then this is already handled.</s>
- <s>Vore mobs check if their target has digestion turned on. **Vore mobs always digest their victims** so if they are set not to digest, they should **not** attempt to eat them and just attack normally.</s>
- <s>If target is edible, and the target is knocked over or laying down, the vore mob will begin swallowing them. If they do not stand up or move away in time, they get swallowed! Swallowing prey should take about the same time as it does for players to eat players.</s>
- Vore emotes should be a variable so they can be changed with different mobs. For example: _var/swallow_emote = "[src] starts swallowing [T] whole!"_ But that way if I have, like, a goo predator, I can change that to _swallow_emote = "[src] starts enveloping [T] in warm goo!"_ Similarly there should be a _var/consume_emote = [src] swallows up the last of [T] and lets up a satisfied belch!"_
- <s>Some vore mobs should update icons for 'full' and 'empty'. If multiple prey is allowed, it'll have several more sprites. Example: icon_state = defaultpred[a], where [a] is the amount of prey in belly (and 0 by default obviously).</s>
- <s>Vore mobs should damage victims at the same rate of all other vore modes in the game.</s>
- <s>If health hits 0, they automatically vomit up their victim(s) **before** executing the rest of the death code, because otherwise the mob risks being deleted on death in some cases.</s>
- <s>Vore mobs should play the gurglynoises to the victim and do emotes about how its gut is squeezing and churning its victim, similar to how it currently works with non-hostile pred mobs.</s>

Placeholder mob icons will use copies of the clown and cluwne mob icons for now, just so we can make sure the code works. Let Joan or Scree worry about programming the first vore mob. (I'm thinking a simple snake would work!)

**Comment by Screemonster** [comment]
Is there gonna be an endopredator variant as well, with the same behaviour except just eating everyone and everything they can on account of harmless? Possibly some sorta stun or holodamage for prey?
Bonus points if they start _running away_ from would-be rescuers with their prize.

**Comment by antsnap** [comment]
I'm not a super fan of ALWAYS digesting, but for the first few mobs yeah sure. Some bad mobs might just want to imprison ;3

These are really good bullet points otherwise thou.

**Comment by SpadesNeil** [comment]
Okay let's make digestion a 1 / 0 var on vore mobs.

**Comment by SpadesNeil** [comment]
Non-digestion mobs are already programmed in. Digestion can actually be controlled by the player for those mobs. These are different and always hostile.

**Comment by Screemonster** [comment]
Yeah, but those mobs aren't _hostile_ with all the stuff that entails. I'd love to see critters that run up, shove you over and gobble you up. Would mean the endo crowd aren't left out of the hostile voremob thing entirely :p

**Comment by SpadesNeil** [comment]
But hostile mobs murder you.

If we want a mob that just knocks you over and noms we can use the existing code.

**Comment by Arokha** [comment]
Yeah, but this is a specific fetishy kinda murder. The same reason we have pref-following required by the rules, e.g. you're allowed to stab anyone to death regardless of what they think (OOCly allowed, I mean) but not allowed to eat them if they are pred-only, or not allowed to eat them in the ways they don't like.

By your logic, we shouldn't have those rules either.

**Comment by SpadesNeil** [comment]
What? No.

We already have code for what Scree wants. Hostile mobs kill people anyway. Hostile mobs appear in gateway missions which are inherently dangerous. They are not being spawned on the damn station.

If you don't want to be digested, the hostile mob is still going to kick the absolute shit out of you. That's never changed.

**Comment by nightwingthedragon** [comment]
Aaaaace, what Scree is asking for is a kind of hostile mob that KIDNAPS, but does not KILL victims. They behave hostile for all intents and purposes, they just run up, knock you down, eat you, and then run away again to give the rest of the players another objective; find the thing and save your team-mate, while not just being "oh welp I guess they're dead better forge on."

Now, to comment on certain parts of your framework...

> Vore mobs should only engage targets who are not in the same faction as they are, obviously.

I'm pretty sure they'll inherit this behaviour just by being "mob/**hostile**/vore", assuming that's what hostile mobs do.

> Swallowing prey should take about the same time as it does for players to eat players.

Much, much, much too long for an action environment. The player will stand up and walk away during the 5 or so seconds the predator would be swallowing them for. And the predator standing still doing nothing but swallowing for all that time will basically be a massive vulnerability period where the other players running the gateway run up and kick the shit out of it. It's gotta be (almost) instant to be viable in the gateway.

-----

You've also kinda forgotten about the fact that by current code, players will be able to beat the crap outta their preds from the inside. We should put a limiter on that or somesuch. Guns shouldn't work for starters, and your attacks would be weaker and/or more infrequent because it's hard to move in there.

**Comment by SpadesNeil** [comment]
Well getting the mob to run away after eating someone isn't something I know how to do. How would we possibly code that? The mob AI isn't smart enough to know how to flee an area.

Also this is blocker as a feature. Blocker means "development / bugtesting / something cannot proceed without this." This is a feature blocker, meaning I cannot begin developing more vore mobs until this is done. Therefore, it blocks development.

If this were a blocker bug, it means a feature already implemented is completely broken.

**Comment by Screemonster** [comment]
Oh, the mobs-spitting-prey-up-when-hit thing is another feature that'd make me want to use these for hostile-ish endomobs rather than the pets. (although porting that to the pets would also be a good thing to do, along with SOME way of getting out of them without OOC escape or killing them)

Would the spit-up be automatic upon death, or a chance based upon current health (which would have the same effect) or just a flat % per hit?

**Comment by Screemonster** [comment]
Had another little think about this and some of the distinction between these mobs and the existing pets and endomobs has made me ask myself "why are we doing it this way anyway?"

It seems to me that it'd be more consistent to add a few variables to _all_  mobs to configure how they behave when it comes to noms. Seems a bit silly to make hostile voremobs as their own thing and snowflakecode everything else, rather than using a standard way of doing stuff.

Do they digest by default?
Can digestion be toggled by adjacent players like the current pets?
What %chance is there of releasing prey upon taking damage?
Will they release prey when prompted by someone outside? (see #596 for an issue about getting people out of nonhostile voremobs like Runtime)

Obviously for /hostile/vore mobs on the gateway levels Ace has in mind the answers for these are likely to be yes, no, some and no respectively.

**Comment by SpadesNeil** [comment]
I want hostile vore mobs to be separate on purpose because they use different code not used by normal mobs.

Vore mobs use their attack during the attack proc, and other mobs NEVER USE THIS PROC EVER.

This is intentional because otherwise it demands excessive code like checking for allies and I don't want it possible to toggle digestion off by players and hostile vore mobs also utilize extra sprites which other mobs do not.

**Comment by Screemonster** [comment]
Makes sense.

**Comment by SpadesNeil** [comment]
There are major changes being made to the vore code so I'm going to handle this instead, since all simple_mobs now have a nom proc attached to them. All I need to do is make it work with an AI.

**Comment by Arokha** [comment]
> Vore mobs should have basic code framework under /mob/living/simple_animal/hostile/vore and I'll worry about adding additional mobs.

The proc on simple_animal is called animal_nom(). Call it with animal_nom(target). Target must be a mob/living.

> Vore mobs should check if their target is human or monkey. If not, don't execute vore code and just attack normally.

Unnecessary now. All /mob/living can be eaten and digested by any other /mob/living.

> If target is edible, and the target is knocked over or laying down, the vore mob will begin swallowing them. If they do not stand up or move away in time, they get swallowed! Swallowing prey should take about the same time as it does for players to eat players.

animal_nom() uses literally the same code as humans use to eat others. All /mob/living does so if you want to change the time, on the mob's belly, change the time variables, same as anything else.

>Vore mobs should have a random chance of spitting up a victim each time the predator mob receives damage. If health hits 0, they automatically vomit up their victim(s) before executing the rest of the death code, because otherwise the mob risks being deleted on death in some cases.

Make sure you call release_specific_contents(target) with this. And release_all_contents when they die. If you don't, you risk leaving variables weird.

>Vore mobs should play the gurglynoises to the victim and do emotes about how its gut is squeezing and churning its victim, similar to how it currently works with non-hostile pred mobs.

Done automatically in new vore code.

>Vore mobs digesting victims should slowly restore health of the mob. Recovery rate should be decided by a variable. By default: var/digest_recovery = 0.1 so for every tick that the mob damages prey, it regains 0.1 tick of health.

This can either be done on simple_animal or on a new belly mode or something. Could be added to the digestion code in belly_modes.dm that it checks if the owner var is set to type simple_animal and then do healing in that case.

>Vore mobs should damage victims at the same rate of all other vore modes in the game.

This is the case in the new vore code but you can tweak it per-belly if you really want.

>Vore emotes should be a variable so they can be changed with different mobs. For example: var/swallow_emote = "[src] starts swallowing [T] whole!" But that way if I have, like, a goo predator, I can change that to swallow_emote = "[src] starts enveloping [T] in warm goo!" Similarly there should be a var/consume_emote = [src] swallows up the last of [T] and lets up a satisfied belch!"

This is actually NOT done in the new vore code since I didn't want to allow these particular messages to be custom but is trivial to make it coded in for specific mobs.

**Comment by SpadesNeil** [comment]
> This is actually NOT done in the new vore code since I didn't want to allow these particular messages to be custom but is trivial to make it coded in for specific mobs.

I can do this myself specifically for hostile vore mobs.

**Comment by SpadesNeil** [comment]
Okay so I have everything set up sort of, but it's not functioning as expected. If I lay down, the snake doesn't try to eat me.

**Comment by Screemonster** [comment]
Is the eating part of the attack proc?
... 'cause I now have a horrible feeling that hostile mobs don't attack people if they're not standing, specifically so they don't stand there beating on someone who's already in crit/dead while there are still targets in the area. Try it with a nonvorey hostile mob and lie down next to them.

I wasn't sure if that was specifically a reference to the thing of lying down if you see a bear so as not to provoke it, but that was a way to survive on the snow bear level - just hit rest and wait for them to wander off the screen. If that's how _all_ hostile mobs operate, then...

**Comment by SpadesNeil** [comment]
I can always override the code for bears and do something differently like check health instead.
