### ISSUE TITLE
Age limits change

### ISSUE THREAD

**Issue by Treasa729** [SpadesNeil/VOREstation#572]
While it is understandable in the base game for the age to be restricted to the 17 - 85 year range, it seems like something that's a bit out of place in a server like this. It is even stated directly in the Sergal lore that they live incredibly long lifespans, and that there was one who apparently lived for 5000 years. Given this, and the nature of the custom races that many people's characters belong to because of the RP oriented server, it isn't out of place for there to be characters with extended lifespans, for one reason or another. I think that the age cap should definitely be raised to something much higher, (Or uncapped entirely) It seems like a really simple thing to change which would make a lot of sense given this type of server, and the characters who inhabit the station.

**Admin Edit:** We can set it to 200 years, but no higher than this.

**Comment by SpadesNeil** [comment]
> It is even stated directly in the Sergal lore that they live incredibly long lifespans, and that there was one who apparently lived for 5000 years.

But did you read the rest? Because such long lifespans are extremely rare.

I'd be willing to up it to 150 years and not a year further, because beyond that, people who make their characters such extreme ages break all sense of immersion and realism. I've even been considering retconning that Mary Sue portion of the lore for Sergals.

**Comment by Treasa729** [comment]
I did read the rest, but there are also very few people who play Sergals as a species directly, or really any of the species directly, other than human. Many people play dragons who have extended lifespans and such as well, and what do you mean by extreme ages breaking immersion and realism? If to a species, they tend to live for hundreds of years, and as such, people from that species are only truly considered 'adults' at say, 50 years old, it wouldn't be odd for there to be people who stretch that border higher. Also with all of the technological advancement that some species have had, and the ability to teleport, give genetic superpowers like telekinesis, why would being able to have aging slowed down genetically be something that's impossible to overcome? Is that really where we draw the line? We can genetically modify people to be able to have telepathy, and to not need to breathe. We can make people resistant enough to temperature and pressure that with internals, or with the no breathing genetic power, they can spacewalk without anything on them.  You can have X-ray vision, which somehow just lets you see literally everything through walls and physical matter, you can become the damn hulk. I find it silly that you draw the line of immersion breaking and realism at age, and not at any of the absurdly crazy sci-fi fluff stuff that's pulled. Shrinking, teleportation, red space magic, all of those seem far more absurd to me than simply being able to slow down the process of aging. As it stands, it really just stems from the process of how the cells in the body regenerate over time, and perfecting, or improving that process genetically would mean drastically slowed rates of aging, possibly even completely halting it. Keep in mind as well that humans aren't the only species in the galaxy, there are others who could have improved such processes far before the humans managed to obtain the tech for such things. According to our lore, the Skrell modified the genomes of the Akula to be able to survive for sustained periods of time in the open air, is it that big of a leap to be able to modify the genomes to slow down the process of aging? In the end, do what you want, of course, I just feel that you dismissing it completely offhandly like that is an odd decision given what is truly capable in our cannon, anyway.

**Comment by SpadesNeil** [comment]
Limiting things sets a standard and an expectation that is expected to be followed. If I took the limits off things like character skills, a player who has a shitty overpowered character in their head wouldn't think twice before attempting it. Instead it tells the player what is believable.

Speaking of that feature, it's directly tied to age. If I remove the cap on age, I remove the cap on this device which helps players figure out how believable and how overpowered their character might be.

Why is thousands of years not believable? The oldest animal **on the planet** has a lifespan of roughly 200 years, which is the Arctic Whale. Beyond that, even if something could potentially live longer, it probably won't. Yea, technology has come a long way, but the idea that we can just prolonging life indefinitely is not really something that's feasible, and falling back to the warning I presented earlier, opening up that limit also opens up an _invitation_ for people to make **really, really bad characters who will drag down the RP quality of the entire server.** I have no desire to cater to these people.

Speaking of the Skrell, you neglect to understand just how insanely difficult it is to extend a creature's life span with some genetic modifications. It doesn't work that way. It never _will_ work that way. The very nature of DNA its self **break down with age** and no matter how much we try to modify it, it will **keep getting beat to shit** until it's in such a state of disrepair that it cannot be effectively mended any further.

Finally, both a scientific and literary reason against it.

“I just don't think [immortality] is possible,” says Sherwin Nuland, a professor of surgery at the Yale School of Medicine. “Aubrey and the others who talk of greatly extending lifespan are oversimplifying the science and just don't understand the magnitude of the task. His plan will not succeed. Were it to do so, it would undermine what it means to be human.”

Not only is it completely not believable, it takes a massive chunk out of what it means to be human. Yes I know we're alien spacemen on a station orbiting who the fuck knows where, but the philosophy is still relevant in that if you make something like age so carelessly cast aside, it massively degrades the quality of roleplay because it takes any sort of limitation off whatever the heck you feel like knowing how to do. Someone who has lived for that insanely long is going to know an insane amount of skills, and that's overpowered. If they don't, then they spent all that time with their thumbs up their asses and that's not believable. Beyond 200 years, and that's my **absolute limit** on this, it's just not fun anymore.

**Comment by Arokha** [comment]
A funny thing I found in the code the other day:
```
				// Different head positions have different good ages.
				var/good_age_minimal = 25
				var/good_age_maximal = 60
				if(command_position == "Captain")
					good_age_minimal = 30
					good_age_maximal = 70 // Old geezer captains ftw
```

This is in the proc that selects one head at round start (it really tries to fill any one head first, then assigns jobs, then goes back to command positions). If it's trying to pick a captain, it favors 30-70yo characters. If it's trying to pick other heads, it favors 25-60yo characters. Anything younger or older subtracts from how favored they are for head roles and they are less likely to get them (depending on how far away they are from the optimal range).

**Comment by Arokha** [comment]
More on topic, I do like living a long time. I'm very much in support of transhumanism and whatnot. Resleeving between bodies and stuff. And we even have MMI stuff ingame to swap brains between mech bodies, which could lead to functional immortality.

But, like, Ace does have a point, though I think I'll take it a different direction. Why would a 500 year old be working on some crazy-ass space station in the backwaters of space? If they are 500 and superskilled, wouldn't NT want them somewhere else? If they were from some super-advanced race with transhuman stuff, or from just a biologically long-lived race, I'd think NT would just pay for them to move to somewhere else so they can make better use of their skills.

**Comment by SpadesNeil** [comment]
Also, about General Rain, General Rain is Sergal mythology. There is no evidence to claim she was ever an actual person.

So living for 5000 years? How often have we heard extreme life spans in mythology? But that's the _point_. It's a myth. It's something you and I could only ever marvel at (if we were sergals).

**Comment by Treasa729** [comment]
I understand where you're coming from ace, and that is a good point about Sergal Mythology, but at the same time, you're grounding this entirely within modern medical science. Shrinking, and growing in the way that we can in this server would break the laws of our modern sciences if it were actually possible. Taking something, and then shrinking, or creating mass out of nothing? Then at the same time, a creature who shrinks from 6 feet tall to 1 foot tall would have their brain mass decrease to one thirty sixth of what it used to be? They would lose 97.2 repeating percent of their brain matter and still be able to function on the same level as they used to? How the hell do we also take warm blooded creatures and let them survive when their body temperature would plummet so much that they would physically freeze, but they can somehow still move? How can we take the The bodies of the creatures on the station wouldn't even be able to physically support the sheer mass of their bodies when we're talking about massive creatures? How can we take creatures who use oxygen for cellular respiration and just get rid of that need entirely? It's not breathing through some sort of just latent absorption of oxygen, either because it can be done in completely oxygen-less environments. Do none of those things undermine the nature of being human? What about the ability to accelerate growth with cloning to the point where you can grow from being nothing at all to a full fledged person with all the memories you had before without any negative repercussions? You talk about me not understanding the gravity of the task of extending life, but do you understand the gravity of the things that genetics can do? You can literally inject someone with a syringe and have their body completely change from male, to female, to essentially become the identical twin of the person who was scanned **within seconds** using genetics with the SE and UE, you can turn a monkey into your identical, albeit braindead twin over the course of about 10 seconds with two syringes. Is that feasible? From a science perspective, there are too many things that happen on our station which are just completely and utterly impossible with our understanding of science. The application of our modern science to them becomes pretty much completely useless and pointless. Half of the things which are possible just don't make any sense, how the hell does injecting someone with a syringe give them **telepathy, telekinesis and x-ray vision** ? 

I will concede your point for RP purposes, though. And while I do think that the sorts of characters can be done well, it is questionable as to why that would be the case. Though, as for why someone with that much experience would be working on a place like VORE? Maybe just because they want to. Having spent likely hundreds, even thousands of years engaging their brain in crazy complex tasks, constantly under the strain of whatever shit they'd likely be capable of if they were truly that skilled, maybe they just want a vacation? I mean, with the quality of work that comes from VORE, it'd probably be a welcome change from the constant high expectations they'd have set out for themselves with what they're able to accomplish due to their vast knowledge. Maybe they like vore, who knows. There are plenty of people who are capable of much more, or who decline promotions simply because they don't want the sorts of jobs they might be able work. It's understandable though, not wanting to invite people who will just make characters who are just essentially all knowing.

At the end of the day, doing it for RP reasons, I understand, but doing it for scientific reasons is silly given all of the shit which is just impossible given the laws that we believe to govern our universe. I'm not saying that scientifically extending age is easy, just that in comparison to some of the stuff that is in station lore, it is much more trivial than you give it credit for, especially when comparing it to the stuff in genetics which make absolutely no sense, far more so than making someone not age as rapidly. Either way though, I do appreciate that you actually took the time to argue your side of it. I just don't think that the people who are going to make powergamey god characters really give a crap about what the age input is, but that's just me. I feel that if they want to make overpowered characters and give one sentence RP with no punctuation and such, they're going to do so anyway.

One thing you could possibly do is that when people try to input an age above a certain threshold, they get a pop up message which discourages using it as an excuse to powergame, that would in a way be a better way of dissuading people from doing it simply because it's an active sort of dissuasion rather than just a, "Oh, I can't input that high of an age, they just must not understand how my character is the god of hyperdeath." or something along those lines.

**Comment by SpadesNeil** [comment]
Please do not use the excuses of, "Well we can do X, Y, and Z. Why can't we do this?" Because I've heard that excuse a million times across at least seven different franchises ranging from Star Wars to S.T.A.L.K.E.R. as an excuse to include something seemingly benign but actually really bad for the RP.

Writing isn't about "Why not?" It's about "Why?" I wrote a lengthy post about this in another community. "Because they feel like it" is not a good enough excuse for answering that question.

The age limits are staying and that's final. I'm willing to raise it. **I will not allow their removal entirely.**

**Comment by Treasa729** [comment]
Do what you will, it's your server after all, my opinion on the topic obviously differs from yours. I disagree, but that's that :P It's just the way I view things, there are limits to what my suspension of disbelief can cover, and to me, age is something far more minor and much less immersion breaking than some of the other stuff that we're capable of. Genetic superpowers to me completely destroy my immersion. I'm not going to ask them to be removed, because people are allowed to have their fun, and if that's how people have fun, they're allowed to. I think that extending the age limit is another way to help people facilitate that fun, and possibly even bring new or interesting RP to the table. Genetics also has the possibility for interesting RP, but it also has a huge possibility for powergaming, and such too. My opinion is just different on that matter, and that's the end of it. It's an opinion. You can extend the age limit, you can reduce them, you can remove them. At the end of the day, I expressed my opinion on the matter, and that's all I am doing. If my opinion and arguments don't sway you, then they don't. You can do whatever you feel is right, and I will respect that.

**Comment by SpadesNeil** [comment]
To be fair I think some of the genetic superpowers are bullshit too but I also don't let people have those straight from the get-go. We did that once. It was a horrible idea.

Your argument did sway me though at least a bit. I had no intention of changing the age limit at all when this started but after making me research it in an effort to refute you, I see ~200 years as plausible now.

**Comment by Treasa729** [comment]
That's fine with me, I was just throwing out an idea, that's what most of my stuff is here, just me throwing suggestions out there that I think are interesting, whether or not they are also considered such by others is an entirely different matter. Thanks for listening to my arguments rather than just disagreeing and closing it right away though, that happens all too often in other communities I've been in.
