### ISSUE TITLE
Protection from digestion

### ISSUE THREAD

**Issue by Arokha** [SpadesNeil/VOREstation#577]
http://forum.vore-station.net/viewtopic.php?f=20&t=627

Bio stat on armor? Damage based on how far from 100% protection it is? Make damage apply to exposed limbs? Good times.

**Comment by SpadesNeil** [comment]
The way the bio armor thing would work if added is, the way all fully sealed suits ALREADY work is the suit is 70 and the helmet is 30. Together they make 100% protection against bio attacks and any poisons or toxins or viruses in the air.

Bees in the old code worked like this. All hardsuits already have 100% bio protection.

I don't want oxygen or toxin damages to be an option in the future digest() proc because there's simply no reason for it, considering Oxy damage knocks you out really soon and Toxin damage causes internal damage that is harder to fix and it makes you puke your guts up. So don't make Oxygen or Toxin damage an option in the code. It's too much of a headache to deal with. For similar reasons, toxin and suffocation bullets were removed from the code ages ago.

**Comment by SpadesNeil** [comment]
Also there are no suits that have 100% bio protection while leaving limbs exposed. That wouldn't make any sense. If it can leak in to digest any of you, it can digest all of you. Let's not complicate it by targeting specific limbs.

**Comment by Arokha** [comment]
Rolled into #601
