### ISSUE TITLE
Vorey pets (and other simple mobs) need a means of getting prey out.

### ISSUE THREAD

**Issue by Screemonster** [SpadesNeil/VOREstation#596]
Right now the only way of getting prey out of them is with OOC escape.

Suggest some means by which people can prompt non-hostile vorey critters (or nonvorey critters that people have fed themselves/other people to) to release prey without killing them. Personally I'm in favor of whapping their nose with a newspaper simply because a: it's funny, and b: newspapers are relatively easy to acquire while not being a thing that people tend to carry around all the time.

**Comment by Treasa729** [comment]
I would suggest also being able to resist out of it so that people have an IC way to get out of the pets as well on their own since oftentimes people can just not care enough to respond if someone asks for help, or the people with access are in scenes. I'd suggest making it a loong delay, like handcuffs or longer, maybe in the 2-5 minute range to resist out of, that way they're also forced to listen to plenty of the teasy vore critter emotes :3

**Comment by Treasa729** [comment]
I would say this in addition to the newspaper idea since that'd be a funny thing to have as well, but I just think there needs to be a way to get out of them without just OOC escaping if you're on your own.

**Comment by Screemonster** [comment]
with _mobs_ I probably wouldn't mind too much if there was a release probability if the prey squirms with the arrow keys, seeing as how you can't ask them to cough you out.
Just as long as we can varedit it down to 0 when we put a player in control. :9

**Comment by Treasa729** [comment]
Yes, that's the thing, for players you have a way of getting out IC, but for mobs, you don't since you can't interact with the mobs to get you out (Or try to) like you can with people. Definitely don't make it something where people can just escape from wiggling around in people normally :P

**Comment by Arokha** [comment]
FYI now every mob has a vore panel so at least if player/admin-controlled they can be easily released.
