### ISSUE TITLE
EVA airlock cycling wastes air

### ISSUE THREAD

**Issue by ZodiacShadow** [SpadesNeil/VOREstation#66]
Too much air is spent while pressurizing and depressurizing double airlocks, and airlocks in general seem to spend too much to open/close.

**Comment by SpadesNeil** [comment]
I think the airlocks are opening before the room is fully drained. Not sure if intentional, but I think it's stupid, so let's revert it.

**Comment by Leshana** [comment]
This is exacerbated/related to the known map issue for airlocks.

**Comment by Arokha** [comment]
This is not possible to fix without significant ZAS changes as far as I know. The room can't be drained to 0.0000000000000 air. Even draining it to 0.1 takes a VERY long time. Instead it is drained to about 3kpa and then opened.

It's a tradeoff between time and air loss. To compensate for this, we've increased the amount of air in the airlock air cans, so that airlocks don't 'fail' during a shift (they would, if cycled a hundred times, or blown repeatedly, still).

This can probably be closed with this change, as the PR was already merged.

**Comment by SpadesNeil** [comment]
Marking as wontfix, because it's not a feasible fix. Air will always be bled off when opening vents.
