### ISSUE TITLE
Mute OOC during votes

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#721]
It's not fair to the majority of players when people go "scene" to guilt others into swaying their votes.

It's not fair to people waiting patiently to join on a fresh round.

**Comment by antsnap** [comment]
The problem exists but this isn't the solution. If you mute OOC you create an annoyance for those who were using it atm (rare, but still...). Additionally, they will just complain on Skype/Discord. The counter is obvious, ban them from Skype/Discord temporarily. However, that's very harsh and a little rude~

Options
1. Warn people who do the scene guilt stuff
2. Get rid of the vote and make it automatic
3. Just let it go friend.

I prefer 3, since subjectively I've never had an issue with this. If I'm in a scene and the vote comes up, I just hasten the scene or offer to continue it next round. Or, even better, just stay in the dorm and finish it. You don't **need** to get on the damn shuttle every time.

In my experience people will just ignore the beggers in OOC. They know damn well it's been five damn hours already, check your PDA friends. Only time I've seen a vote canceled was when more than half were scening, in which case it should be postponed.

**Comment by SpadesNeil** [comment]
Some people do it all the goddamn time, then have the audacity to get uppity when we vote transfer anyway.

I might just make a rule though.

**Comment by SpadesNeil** [comment]
Re-opening this due to popular demand.
