### ISSUE TITLE
Xenoarch Borgs can not activate the Steadfast. Xenoarch bots can not do their job alone if ordered.

### ISSUE THREAD

**Issue by spirel5** [SpadesNeil/VOREstation#724]
Figured this would be important to know for the coders. Borgs can not activate the Steadfast. Thus the Xenoarch bots can not do their job alone if ordered.
Also had a really weird issue with K9 units and a laser carbine and a giant snake. Somehow the gun was hitting me instead of the giant snake when it was a straight path to him. Not sure if that was bad luck or a bug in the laser carbines aiming path
But it did it three times in a row

**Comment by Cameron653** [comment]
They're designed to not be able to do 100% of xenoarch (Although, I've been informed they _are_ able to go and use the suspension generator), so that's not really that much of a bug.

Also, with the laser carbines, it's not the K9. The K9 laser does nothing different than a normal laser.
Multiple things could've happened depending on the situation. The laser could've missed the target and hit you. The aimer could've been aiming just right to where it zigzagged and hit you before it hit the snake. If it was a 64*64 sprite, then that brings even more problems into the equation. If you could replicate it, I could probably point out the problem or whatnot.

Personally, I'm imagining it was a 64*64 sprite that he was aiming at, and you were at such a way that it zigzagged and hit you. But, I could just be wrong. Really need to know the entire situation in order to actually find the cause.

**Comment by SpadesNeil** [comment]
Please be more descriptive with your issue title in future.

**Comment by SpadesNeil** [comment]
Also I can confirm the laser thing happened and I'm 90% sure it's a hitbox issue.
