### ISSUE TITLE
Maintenance Drones ghosts have no ghost sprite when gibbed

### ISSUE THREAD

**Issue by bear-irl** [SpadesNeil/VOREstation#74]
Spawned in as one earlier to get comfy by myself doing some work cleaning up and made lights in a lot of the maint tunnels, logged off hidden under a rack somwhere and came back later during the same round no longer wanting to be a drone.
Robotic storage doesn't work for them so I tried to suicide and leave my body in an out of the way place, it was taking way too long to drain the battery for suicide so I shut myself in a bolted construction airlock away from active players and bludgeoned myself to death with a wrench.
Ghost was invisible when I did finally ghost, possibly because I exploded and they have no brain/posibrain? Being able to use robotic storage silently or some other way of leaving the round to respawn would be nice.

**Comment by SpadesNeil** [comment]
Having no ghost sprite upon death is a result of not having a positronic or any kind of brain, yes. I believe this is intentional but there needs to be a backup ghost sprite instead. I will attempt to remedy this later by making a default sprite for the file.

As for not being able to use robotic storage, considering the disposable nature of drones, I believe there is a better way to handle it. Maybe the drone fabricator should have a feature to dismantle drones if it does not already.

Drones are highly expendable. If someone finds you shut down and you're in the way, they can just break you. Kind of like mice, but more useful. They can only RP with other drones.

**Comment by SpadesNeil** [comment]
Maintenance drones being disallowed from using the robotic storage appears to be intentional.

**Comment by SpadesNeil** [comment]
Due to the current way ghosts work, this cannot be properly fixed.
