### ISSUE TITLE
Inconsistent micro tile placement

### ISSUE THREAD

**Issue by SpadesNeil** [SpadesNeil/VOREstation#82]
Micros and small characters should be centered on tiles just due to the simple fact that ABSOLUTELY NOTHING LOOKS CORRECT under them if they are not centered on the tile.

The only thing that looks nice is walking. That's it.

I strongly feel we should make it so small and micro are centered on tiles and not offset, otherwise putting them on tables and on chairs looks stupid and broken.

@nightwingthedragon

**Comment by nightwingthedragon** [comment]
I'm gonna still be looking into this because I don't like the inconsistency with large players; they align to the bottom while micros don't. But the graphical bugs are something I gotta work around. If I could set it so that position in the tile was decided by what was in the tile, that'd be fantastic. But for now, I'll re-add the code that centres them.

**Comment by SpadesNeil** [comment]
All small mobs appear on the center of the tile as well, excluding lizards, which were changed to match this consistency. Micros are the outlying variable.

Macros on the other hand align with the bottom of the tile, because that's how every sprite bigger than 32x32 is. The only exception is the singularity, which is not attached to the ground, and rather, floats around.
