### ISSUE TITLE
Sprites: Blue Akula blood added to certain containers turns blood red!

### ISSUE THREAD

**Issue by ArbyTheDragon** [SpadesNeil/VOREstation#98]
Akula blood sitting in a LARGE (120u) beaker is dark blue as it should be. But if this blue blood is added to a bottle OR a small beaker (60u) through any method- the blood turns red and retains the default red color!

I do not know if it does the same for glasses, like the ones from the bar.

**Comment by SpadesNeil** [comment]
Honestly I think Akula blood should just be red to begin with.

I also do not think this is possible to fix due to the limitations of the game engine. Will probably mark as wontfix. It's because when we re-added Akula, we changed their blood color to match that of Skrell. Really, blue blood doesn't make a ton of sense for Akula. They're not horseshoe crabs.

Leaving this issue open as a bug / wontfix, only because I do want to change akula blood color and this will remind me to do that.

**Comment by ArbyTheDragon** [comment]
B-but I like the blue color :<

**Comment by ShadowLarkens** [comment]
This isn't a byond limitation, it's shitty bay code not applying to all beakers consistantly.

**Comment by ArbyTheDragon** [comment]
Then don't fix it and leave it the way it is! I LOVE HAVING BLUE BLUE BLOOD D:

**Comment by SpadesNeil** [comment]
Allow me to rephrase that, then. A Bay limitation.

But also we can change that. I removed Wontfix.

**Comment by SpadesNeil** [comment]
Marking as wontfix because it's such a minor issue.
